services:
  - type: web
    name: crime-eye-backend
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y \
      cmake \
      build-essential \
      libopenblas-dev \
      liblapack-dev \
      libx11-dev \
      libgtk-3-dev
      pip install -r requirements.txt
    startCommand: python app.py
